name: qsv Debian Package

on:
  workflow_dispatch:

jobs:
  analyze-tags:
    runs-on: ubuntu-20.04
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

  build:
    needs: analyze-tags
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Install Cargo Deb
        run: cargo install cargo-deb

      - name: Build Debian Package
        run: cargo deb

      - name: Upload Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: qsv-deb
          path: target/debian/*
      
  push:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: tino097/qsv-deb-releases
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
      - name: Setup Git
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions"
      - name: Download Debian Package
        uses: actions/download-artifact@v2
        with:
          name: qsv-deb
      
      - name: Commit and Push
        run: |
          git add .
          git commit -m "Add Debian Package"
          git push



