name: Publish Debian Package

on:
  workflow_dispatch:

env:
  QSV_KIND: prebuilt

jobs:                
  analyze-tags:
    runs-on: ubuntu-22.04
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

  build:
    needs: analyze-tags
    runs-on: ubuntu-22.04
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.analyze-tags.outputs.previous-tag }}

      - name: apt-get update Ubuntu, libwayland-dev
        run: |
          sudo apt-get update
          sudo apt-get install libwayland-dev

      - name: Install Cargo Deb
        run: cargo install cargo-deb

      - name: Build Debian Package
        run: cargo deb --target=x86_64-unknown-linux-gnu

      - name: Upload Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: qsv-deb
          path: target/x86_64-unknown-linux-gnu/debian/*.deb

