name: qsv Debian Package

on:
  workflow_dispatch:

jobs:                
  analyze-tags:
    runs-on: ubuntu-20.04
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

  build:
    needs: analyze-tags
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Install Cargo Deb
        run: cargo install cargo-deb

      - name: Build Debian Package
        run: cargo deb

      - name: Upload Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: qsv-deb
          path: target/debian/*
      
  push:
    needs: build
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          repository: tino097/qsv-deb-releases
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Download Debian Package
        uses: actions/download-artifact@v2
        with:
          name: qsv-deb
          path: target/debian

      - name: Commit and Push
        id: push_deb_package
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_directory: target/debian
          destination-github-username: 'tino097'
          destination-repository-name: 'qsv-deb-releases'
          commit_message: 'Add Debian Package'
          target_branch: main
