name: Linux Nightly using Polars pinned nightly version

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.12'
    - name: Install and Run Redis
      run: |
        sudo apt-get install redis-server
        sudo service redis-server start
    - name: Installing Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        # get nightly version Polars is using
        # https://github.com/pola-rs/polars/blob/main/rust-toolchain.toml
        toolchain: nightly
        profile: minimal
        components: rust-src
        target: x86_64-unknown-linux-gnu
        override: true
        default: true
    - name: Run tests
      env:
        RUSTFLAGS: -C target-feature=+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+avx2,+fma,+bmi1,+bmi2,+lzcnt,+pclmulqdq
      run: cargo test --verbose --locked --features=apply,fetch,foreach,geocode,luau,python,feature_capable,nightly,polars
